### ISSUE TITLE
电梯调度

### ISSUE THREAD

**Issue by forAlgorithm** [PaddlePaddle/MetaGym#29]
电梯调度的事例太简单了，可以给了引入了强化学习算法的例子不

**Comment by TomorrowIsAnOtherDay** [comment]
有的，请参考PARL仓库里的[DQN示例](https://github.com/PaddlePaddle/PARL/tree/r1.2/examples/LiftSim_baseline)。

**Comment by Ricardoliyan** [comment]
> 有的，请参考PARL仓库里的[DQN示例](https://github.com/PaddlePaddle/PARL/tree/r1.2/examples/LiftSim_baseline)。

为什么现在这个DQN示例代码跑不通呢

**Comment by Cizel0321** [comment]
我也跑不通，感觉问题挺多的

**Comment by TomorrowIsAnOtherDay** [comment]
DQN 运行过程中有什么问题呢？

**Comment by Cizel0321** [comment]
有机会私聊嘛

**Comment by Cizel0321** [comment]
您好，我最近在做这一块的东西。具体去调通的话有点费劲，请问您那边有已经能跑通了的程序或者教程嘛。
可以有偿，万分感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/MetaGym"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月30日(星期天) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/MetaGym] 电梯调度 (#29)





 
DQN 运行过程中有什么问题呢？
