### ISSUE TITLE
How to run it on the real A1 robot?

### ISSUE THREAD

**Issue by df700000** [PaddlePaddle/MetaGym#50]
How to run it on the real A1 robot?

**Comment by WorldEditors** [comment]
RLSchool (or MetaGym) is a simulation environment. The key is that you can pre-train your control policy in the environment and then transfer it to the real robot (Sim2Real Transfer).

By "How to run it on the real A1 robot", I'm not sure if you want to ask how to transfer your learned policy from simulation to real robot, or does it mean something different?

**Comment by xxd-xy** [comment]
I have the same questions?

**Comment by TomorrowIsAnOtherDay** [comment]
Hello, thanks for your interest in our repository. I guess that you want to reproduce the paper that we released recently. There are some suggestions for this question:
1) follow the algorithm details in the [paper](https://arxiv.org/pdf/2109.06409.pdf) and reproduce the algorithm **in simulation** at first.
2) deploy the trained controller in A1-robot following the APIs provided by the Unitree.
3) if the trained controller performs badly in A1, follow the details in `sim-to-real` section of the paper to address the problem. 
Feel free to ask here if you have any more questions.

**Comment by xxd-xy** [comment]
> Hello, thanks for your interest in our repository. I guess that you want to reproduce the paper that we released recently. There are some suggestions for this question:
> 
> 1. follow the algorithm details in the [paper](https://arxiv.org/pdf/2109.06409.pdf) and reproduce the algorithm **in simulation** at first.
> 2. deploy the trained controller in A1-robot following the APIs provided by the Unitree.
> 3. if the trained controller performs badly in A1, follow the details in `sim-to-real` section of the paper to address the problem.
> 
> Feel free to ask here if you have any more questions.

OK !  Thank you very much !!!
