### ISSUE TITLE
关于电梯调度模拟环境

### ISSUE THREAD

**Issue by JACK-ZHANGCHEN** [PaddlePaddle/MetaGym#70]
您好，我在使用liftsim 仿真环境时，出现AttributeError：module  'pyglet.gt' has no attribute 'get_current_context'请问如何解决？

**Comment by WorldEditors** [comment]
想问下目前使用的pyglet版本是多少？LiftSim使用的pyglet版本是1.5.0，推荐使用该版本。
可以
```
pip install metagym[liftsim]
```
会自动安装对应版本依赖

**Comment by JACK-ZHANGCHEN** [comment]
AttributeError: module 'PIL.Image' has no attribute 'fromstring'请问这个问题如何解决？

**Comment by WorldEditors** [comment]
这个应该是PIL升级导致的。新版本的PIL.Image 把接口改成frombytes。可以先用如下方式处理。
1. 把Metagym中调用fromstring改成frombytes
2. 降低PIL的版本
后续版本升级我们会尝试修复这个问题。
